on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Set up JDK 21
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Install cargo-android
        shell: bash
        run: |
          cargo install \
              --git https://github.com/chenxiaolong/cargo-android \
              --tag v0.1.4

      - name: Install toolchains
        shell: bash
        run: |
          rustup target add aarch64-linux-android
          rustup target add thumbv7neon-linux-androideabi
          rustup target add x86_64-linux-android

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebug -x assembleRelease
